/- GENERATED by scripts/gen-policy.mjs from rules/policy.json. Do not edit. -/

namespace Guard

structure Limits where
  maxNodes : Nat := 5000
  maxDepth : Nat := 32
  maxTextLength : Nat := 20000
  maxTotalText : Nat := 200000
  maxAttrs : Nat := 24
  maxAttrValueLength : Nat := 2000
  maxPathNumbers : Nat := 4000
  maxPointsNumbers : Nat := 2000
  maxNumberMagnitude : Nat := 1000000
  maxTraversalDepth : Nat := 256

def limits : Limits := {}

end Guard
