// Build: bundle the frame script, the QuickJS worker and the demo; extract the
// class allowlist from the bundled stylesheet; hash script and CSS for the
// frame CSP; write dist/frame-manifest.json.
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dist = resolve(rootDir, "dist");
const cdn = resolve(rootDir, "cdn");
mkdirSync(dist, { recursive: true });
mkdirSync(cdn, { recursive: true });

const css = readFileSync(resolve(rootDir, "demo/app.css"), "utf8");
// Every class selector in the bundled stylesheet is a permitted class name.
const classes = Array.from(new Set(Array.from(css.matchAll(/\.([A-Za-z_][\w-]*)/g), (m) => m[1]))).sort();

const frame = await build({
  entryPoints: [resolve(rootDir, "src/frame.js")],
  bundle: true,
  format: "iife",
  write: false,
  minify: false,
  target: ["es2020"],
  define: { __CLASS_ALLOWLIST__: JSON.stringify(classes) },
});
let script = frame.outputFiles[0].text;
// The script is inlined into a <script> element; make sure it can never close it.
if (/<\/script/i.test(script)) throw new Error("frame bundle contains </script");
if (/<\/style/i.test(css)) throw new Error("stylesheet contains </style");

const sha256b64 = (s) => createHash("sha256").update(s, "utf8").digest("base64");
const manifest = {
  script,
  css,
  classes,
  scriptHash: sha256b64(script),
  cssHash: sha256b64(css),
};
writeFileSync(resolve(dist, "frame-manifest.json"), JSON.stringify(manifest));
writeFileSync(resolve(dist, "frame-manifest.js"), "export default " + JSON.stringify(manifest) + ";\n");

// ---------------------------------------------------------------------------
// The Lean/Wasm checker, embedded as base64.
//
// The policy Worker payload has to be self-contained -- a cross-origin Worker
// URL fails on every engine under every CSP, and a static top-level import in
// a module Worker fails with no violation report -- so the checker bytes
// travel inside the bundle. The alternative, fetching `guard.wasm`, would
// require widening the host policy to `connect-src <cdn>`; Profile A ships
// `connect-src 'none'` and embedding keeps it. It also makes "the deployed
// bytes are the bytes that were built and tested" one artifact to hash rather
// than an artifact plus a fetch.
//
// Base64 costs +33%. The numbers are recorded in the asset manifest and the
// README; reducing them is Phase 6's job, not this one's.
const checkerWasmPath = resolve(rootDir, "lean/wasm/dist/guard.wasm");
const checkerGluePath = resolve(rootDir, "lean/wasm/dist/guard.mjs");
for (const required of [checkerWasmPath, checkerGluePath]) {
  if (!existsSync(required)) {
    throw new Error(
      `${relative(rootDir, required)} is missing. The distribution embeds the Lean checker, so it cannot be built `
      + "without it: run `npm run wasm:build` (Docker) first. There is no JavaScript-only bundle variant, because "
      + "Lean/Wasm is the acceptance authority and a bundle without it could not render anything.",
    );
  }
}
const checkerModules = readFileSync(resolve(rootDir, "lean/wasm/dist/import-closure.txt"), "utf8").trim().split("\n");
if (!checkerModules.includes("Guard.Wasm") || checkerModules.some(m => /^Guard[.]Props(?:[.]|$)/.test(m) || ["Guard", "Guard.Policy.Check", "Guard.Io.Api"].includes(m))) {
  throw new Error("reference code in production checker import closure");
}
const checkerWasm = readFileSync(checkerWasmPath);
const checkerWasmSha256 = createHash("sha256").update(checkerWasm).digest("hex");
const checkerEncoding = process.env.GUARD_WASM_EMBEDDING || "base64";
if (!["base64", "gzip-base64"].includes(checkerEncoding)) throw new Error("unknown checker embedding");
const checkerEncoded = checkerEncoding === "gzip-base64" ? gzipSync(checkerWasm, { level: 9 }) : checkerWasm;
const checkerBase64 = checkerEncoded.toString("base64");
writeFileSync(
  resolve(dist, "lean-checker-wasm.js"),
  "// GENERATED by scripts/build.mjs from lean/wasm/dist/guard.wasm. Do not edit.\n"
  + "//\n"
  + "// `bytes` and `sha256` are recorded so the decoder can check that what it\n"
  + "// decoded is the length the build embedded, and so the asset manifest can\n"
  + "// name the exact binary this bundle carries. A hash binds contents and\n"
  + "// detects a mismatch; it does not prove provenance.\n"
  + "export default " + JSON.stringify({
    bytes: checkerWasm.byteLength,
    sha256: checkerWasmSha256,
    builtFrom: "lean/wasm/dist/guard.wasm",
    encoding: checkerEncoding,
    base64: checkerBase64,
  }) + ";\n",
);

// The Emscripten glue is built for `web,worker,node`, so it contains one
// Node-only branch: `if (ENVIRONMENT_IS_NODE) { const { createRequire } =
// await import("module"); ... }`. That branch is dead in a browser Worker, but
// esbuild still has to resolve the specifier. Stubbing it keeps the payload
// SELF-CONTAINED -- no `import` of any kind survives in the output, which is
// what `assertSelfContainedWorker` and `scripts/check-cdn.mjs` require -- and
// the stub throws if it is ever actually reached, so a Node path can never be
// taken silently in a browser.
//
// `import.meta.url` is defined away because the IIFE format has no
// `import.meta`. It must be defined to a VALID ABSOLUTE URL, not a placeholder
// token: Emscripten computes `wasmBinaryFile = new URL("guard.wasm",
// import.meta.url).href` eagerly, before it notices that `wasmBinary` was
// supplied, and `new URL()` throws on a base it cannot parse. With a
// placeholder the policy Worker failed to start with
// "Failed to construct 'URL': Invalid URL" -- observed on Chromium 140.
//
// The value is a reserved-TLD origin that can never resolve, and it is never
// fetched: the checker bytes come from `wasmBinary`, the host policy ships
// `connect-src 'none'`, and `scripts/browser-check.mjs` asserts on every
// engine that no request for a `.wasm` asset is ever made.
const NODE_ONLY_BUILTINS = ["module", "fs", "path", "url", "crypto", "os", "worker_threads"];
const nodeStubPlugin = {
  name: "node-builtin-stub",
  setup(buildApi) {
    const filter = new RegExp(`^(node:)?(${NODE_ONLY_BUILTINS.join("|")})$`);
    buildApi.onResolve({ filter }, (args) => ({ path: args.path, namespace: "node-stub" }));
    buildApi.onLoad({ filter: /.*/, namespace: "node-stub" }, (args) => ({
      contents:
        `const refuse = () => { throw new Error(${JSON.stringify(`this payload is browser-only; the Node builtin "${args.path}" is not available in it`)}); };\n`
        + "export const createRequire = refuse;\n"
        + "export const readFileSync = refuse;\n"
        + "export const fileURLToPath = refuse;\n"
        + "export default { createRequire: refuse, readFileSync: refuse, fileURLToPath: refuse };\n",
      loader: "js",
    }));
  },
};
const workerBundleOptions = {
  plugins: [nodeStubPlugin],
  define: { "import.meta.url": JSON.stringify("https://embedded.guard.invalid/policy-worker.js") },
};

const worker = await build({
  entryPoints: [resolve(rootDir, "src/runtime/worker.js")],
  bundle: true,
  format: "iife",
  write: false,
  target: ["es2020"],
  platform: "browser",
});
const workerSource = worker.outputFiles[0].text;
writeFileSync(resolve(dist, "worker.js"), workerSource);

const workerMin = await build({
  entryPoints: [resolve(rootDir, "src/runtime/worker.js")],
  bundle: true,
  format: "iife",
  write: false,
  minify: true,
  target: ["es2020"],
  platform: "browser",
});
const workerMinSource = workerMin.outputFiles[0].text;
writeFileSync(resolve(cdn, "worker.min.js"), workerMinSource);

// Policy Worker: bounded parse5 preprocessing and candidate construction. It
// never executes generated JavaScript. The unminified build is what the demos
// load from /dist; the minified one is embedded in the full CDN bundle.
const policyWorker = await build({
  entryPoints: [resolve(rootDir, "src/policy-worker.js")],
  bundle: true,
  format: "iife",
  write: false,
  target: ["es2020"],
  platform: "browser",
  ...workerBundleOptions,
});
writeFileSync(resolve(dist, "policy-worker.js"), policyWorker.outputFiles[0].text);

const policyWorkerMin = await build({
  entryPoints: [resolve(rootDir, "src/policy-worker.js")],
  bundle: true,
  format: "iife",
  write: false,
  minify: true,
  target: ["es2020"],
  platform: "browser",
  ...workerBundleOptions,
});
const policyWorkerMinSource = policyWorkerMin.outputFiles[0].text;
writeFileSync(resolve(cdn, "policy-worker.min.js"), policyWorkerMinSource);

// ---------------------------------------------------------------------------
// Worker payloads must be SELF-CONTAINED.
//
// Both Workers are created from blob: URLs (src/startup.js), for two reasons
// established by the browser spike:
//
//   * `new Worker("https://cdn/...")` fails on Chromium, Firefox and WebKit
//     under every CSP including no CSP, because a dedicated worker's script is
//     fetched same-origin. So the payload has to be inside the bundle.
//   * A static top-level `import` inside a module Worker is checked against
//     `worker-src`, not `script-src`, and when it fails it produces an opaque
//     `error` event and NO violation report on any engine. That failure looks
//     like an unexplained dead Worker, so it must be impossible to ship.
//
// Assert both here, at the point the bytes are produced. A dynamic
// `await import()` would be checked against script-src and is the only
// acceptable runtime import; these bundles have neither.
function assertSelfContainedWorker(name, source) {
  if (/(^|[\s;}])import\s*[("'`{*]/.test(source) || /\bfrom\s*["'`]/.test(source)) {
    throw new Error(`${name}: worker payload contains an import; it must be self-contained (see src/startup.js)`);
  }
  if (/\bimportScripts\s*\(/.test(source)) {
    throw new Error(`${name}: worker payload calls importScripts; it must be self-contained`);
  }
  if (source.length < 1000) throw new Error(`${name}: worker payload is implausibly small (${source.length} bytes)`);
}
for (const [name, source] of [
  ["dist/worker.js", workerSource],
  ["cdn/worker.min.js", workerMinSource],
  ["dist/policy-worker.js", policyWorker.outputFiles[0].text],
  ["cdn/policy-worker.min.js", policyWorkerMinSource],
]) {
  assertSelfContainedWorker(name, source);
}

// The two Worker payloads, as virtual modules. Used by the full CDN bundle and
// by the demo bundles, so the demos exercise exactly the blob: Worker path a
// cross-origin consumer gets instead of a same-origin `new Worker("/dist/..")`
// that would silently run with no inherited CSP at all.
const embeddedWorkerPlugin = {
  name: "embedded-worker",
  setup(buildApi) {
    buildApi.onResolve({ filter: /^guard:worker-source$/ }, () => ({ path: "worker", namespace: "guard" }));
    buildApi.onResolve({ filter: /^guard:policy-worker-source$/ }, () => ({ path: "policy-worker", namespace: "guard" }));
    buildApi.onLoad({ filter: /^worker$/, namespace: "guard" }, () => ({
      contents: `export default ${JSON.stringify(workerMinSource)}`,
      loader: "js",
    }));
    buildApi.onLoad({ filter: /^policy-worker$/, namespace: "guard" }, () => ({
      contents: `export default ${JSON.stringify(policyWorkerMinSource)}`,
      loader: "js",
    }));
  },
};

for (const minify of [false, true]) {
  await build({
    entryPoints: [resolve(rootDir, "src/cdn.js")],
    bundle: true,
    format: "esm",
    outfile: resolve(cdn, `generative-web-guard${minify ? ".min" : ""}.js`),
    minify,
    target: ["es2020"],
    platform: "browser",
  });
}

await build({
  entryPoints: [resolve(rootDir, "src/cdn-full.js")],
  bundle: true,
  format: "esm",
  outfile: resolve(cdn, "generative-web-guard.full.min.js"),
  minify: true,
  target: ["es2020"],
  platform: "browser",
  plugins: [embeddedWorkerPlugin],
});

// Opt-in development linter. Kept out of the default entry point so Acorn is
// not in the default dependency path.
await build({
  entryPoints: [resolve(rootDir, "src/cdn-lint.js")],
  bundle: true,
  format: "esm",
  outfile: resolve(cdn, "generative-web-guard.lint.js"),
  minify: false,
  target: ["es2020"],
  platform: "browser",
});

// Demo bundles. They get the embedded-worker plugin too, so both demos create
// their Workers from blob: URLs with the payload inside the bundle, exactly
// like a cross-origin consumer. demo/cdn.js does not need the plugin: it
// dynamically imports the shipped bundle from the other origin at runtime and
// has no embedded payload of its own, which is the point of that page.
for (const [entry, out] of [
  ["demo/main.js", "demo.js"],
  ["demo/showcase.js", "showcase.js"],
  ["demo/cdn.js", "cdn.js"],
]) {
  await build({
    entryPoints: [resolve(rootDir, entry)],
    bundle: true,
    format: "esm",
    outfile: resolve(dist, out),
    target: ["es2020"],
    platform: "browser",
    plugins: [embeddedWorkerPlugin],
  });
}

// ---------------------------------------------------------------------------
// Asset manifest.
//
// WHAT A HASH HERE DOES AND DOES NOT DO
//
// Each entry binds the CONTENTS of one shipped artifact. Together they let a
// verifier answer "are the bytes in cdn/ the bytes this build produced?" and
// they make a stale artifact -- a rebuilt checker with a forgotten bundle, or
// the reverse -- a detectable mismatch instead of a silent inconsistency.
// `scripts/check-cdn.mjs` checks exactly that.
//
// They do NOT prove provenance. A hash says nothing about who produced the
// input, whether the toolchain was the pinned one, or whether the Lean sources
// that generated `guard.wasm` are the sources in this checkout. Those come
// from building in CI from the checkout and from the proof audit, not from
// this file. Nothing here is signed.
//
// The manifest is deterministic: sorted keys, no timestamps, no build host, no
// absolute paths. Two builds of the same sources produce byte-identical
// output, which is what `npm run build` twice plus a diff checks.
const manifestFiles = [
  "cdn/generative-web-guard.js",
  "cdn/generative-web-guard.min.js",
  "cdn/generative-web-guard.full.min.js",
  "cdn/generative-web-guard.lint.js",
  "cdn/policy-worker.min.js",
  "cdn/worker.min.js",
  "lean/wasm/dist/guard.mjs",
  "lean/wasm/dist/guard.wasm",
];
const sha256hex = (buffer) => createHash("sha256").update(buffer).digest("hex");
const assets = {};
for (const name of manifestFiles.sort()) {
  const bytes = readFileSync(resolve(rootDir, name));
  assets[name] = { bytes: bytes.byteLength, sha256: sha256hex(bytes) };
}
const assetManifest = {
  manifestVersion: 1,
  note: "sha256 of each shipped artifact. These bind build CONTENTS and detect a stale or mismatched artifact. They do not prove provenance: nothing here is signed, and a hash says nothing about which toolchain or which sources produced the input. Deterministic by construction -- sorted keys, no timestamps.",
  checker: {
    // The acceptance authority. `embeddedIn` names the payloads that carry the
    // binary inline, because a fetched .wasm would need connect-src and the
    // Worker payload must stay self-contained.
    entry: "Guard.Wasm",
    modules: checkerModules,
    wasmBytes: checkerWasm.byteLength,
    wasmSha256: checkerWasmSha256,
    encoding: checkerEncoding,
    embeddedBytes: checkerEncoded.byteLength,
    base64Chars: checkerBase64.length,
    embeddedIn: ["cdn/policy-worker.min.js", "cdn/generative-web-guard.full.min.js"],
    fetched: false,
  },
  frame: { scriptBytes: script.length, scriptHash: manifest.scriptHash, cssBytes: css.length, cssHash: manifest.cssHash, classes: classes.length },
  assets,
};
const assetManifestText = JSON.stringify(assetManifest, null, 2) + "\n";
writeFileSync(resolve(dist, "asset-manifest.json"), assetManifestText);
writeFileSync(resolve(cdn, "asset-manifest.json"), assetManifestText);

const kib = (n) => `${(n / 1024).toFixed(0)} KiB`;
console.log(`built: frame ${script.length} bytes, ${classes.length} classes, self-contained QuickJS + policy worker payloads, lint entry, demos, CDN modules`);
console.log(`checker: ${kib(checkerWasm.byteLength)} wasm embedded as ${kib(checkerBase64.length)} of base64, sha256 ${checkerWasmSha256.slice(0, 16)}...`);
for (const [name, entry] of Object.entries(assets)) console.log(`  ${name} ${kib(entry.bytes)} ${entry.sha256.slice(0, 12)}`);
