// Generates src/rules.js and lean/Guard/Rules.lean from rules/catalog.json.
//
//   node scripts/gen-rules.mjs          # write both files
//   node scripts/gen-rules.mjs --check  # exit 1 if either file differs from what would be generated
//
// The catalog is the single source of truth for rule ids. Both checkers cite
// these ids in change records, so the two generated files must always match
// the catalog; `npm test` runs the --check form first.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const catalogPath = resolve(root, "rules/catalog.json");
const outputs = {
  js: resolve(root, "src/rules.js"),
  lean: resolve(root, "lean/Guard/Rules.lean"),
};

export function loadCatalog() {
  const catalog = JSON.parse(readFileSync(catalogPath, "utf8"));
  validate(catalog);
  return catalog;
}

const ID_RE = /^R-[A-Z]+-[A-Z0-9]+(-[A-Z0-9]+)*$/;
const CVE_RE = /^CVE-\d{4}-\d{4,}$/;
const SEVERITIES = new Set(["critical", "high", "medium", "low"]);
const ENGINES = new Set(["js", "lean"]);

export function validate(catalog) {
  const errors = [];
  const seen = new Set();
  for (const r of catalog.rules) {
    if (!ID_RE.test(r.id)) errors.push(`${r.id}: id does not match ${ID_RE}`);
    if (seen.has(r.id)) errors.push(`${r.id}: duplicate id`);
    seen.add(r.id);
    if (!(r.class in catalog.classes)) errors.push(`${r.id}: unknown class ${r.class}`);
    if (!SEVERITIES.has(r.severity)) errors.push(`${r.id}: unknown severity ${r.severity}`);
    if (!Array.isArray(r.engines) || r.engines.length === 0 || !r.engines.every((e) => ENGINES.has(e))) errors.push(`${r.id}: engines must be a non-empty subset of js, lean`);
    if (typeof r.title !== "string" || typeof r.statement !== "string") errors.push(`${r.id}: title and statement are required`);
    for (const k of ["mechanisms", "cites", "proofs", "references"]) if (!Array.isArray(r[k])) errors.push(`${r.id}: ${k} must be an array`);
    for (const ref of r.references ?? []) {
      if (ref.type === "cve") {
        if (!CVE_RE.test(ref.id ?? "")) errors.push(`${r.id}: bad CVE id ${ref.id}`);
        if (!ref.verified) errors.push(`${r.id}: CVE ${ref.id} lacks a verified date`);
      } else if (ref.type === "writeup") {
        if (ref.id) errors.push(`${r.id}: writeup references must not carry an id`);
      } else errors.push(`${r.id}: unknown reference type ${ref.type}`);
      if (!ref.url) errors.push(`${r.id}: reference without url`);
    }
  }
  if (errors.length) throw new Error("catalog invalid:\n  " + errors.join("\n  "));
}

// Cited files are checked by scripts/rule-coverage.mjs, which fails the build;
// here they are only reported so the catalog can name files before they exist.
export function missingCites(catalog) {
  const missing = [];
  for (const r of catalog.rules) for (const c of r.cites ?? []) {
    const file = c.split("#")[0];
    if (!existsSync(resolve(root, file))) missing.push(`${r.id}: ${file}`);
  }
  return missing;
}

export const constName = (id) => id.replace(/^R-/, "").replace(/-/g, "_");

export function renderJs(catalog) {
  const lines = [
    "// GENERATED by scripts/gen-rules.mjs from rules/catalog.json. Do not edit.",
    "// Rule ids cited in change records by src/policy.js. The Lean checker uses",
    "// the same ids from lean/Guard/Rules.lean; the differential compares them.",
    "",
    "export const RULES = Object.freeze({",
    ...catalog.rules.map((r) => `  ${constName(r.id)}: ${JSON.stringify(r.id)},`),
    "});",
    "",
    "export const RULE_IDS = Object.freeze(Object.values(RULES));",
    "",
    "export const RULE_CLASSES = Object.freeze({",
    ...catalog.rules.map((r) => `  ${JSON.stringify(r.id)}: ${JSON.stringify(r.class)},`),
    "});",
    "",
    "export function isRule(id) {",
    "  return RULE_IDS.includes(id);",
    "}",
    "",
  ];
  return lines.join("\n");
}

export function renderLean(catalog) {
  const lines = [
    "/- GENERATED by scripts/gen-rules.mjs from rules/catalog.json. Do not edit. -/",
    "",
    "/-!",
    "Rule ids cited in change records by the policy. `src/rules.js` carries the",
    "same ids for the JavaScript checker; the differential compares them.",
    "-/",
    "",
    "namespace Guard.R",
    "",
    ...catalog.rules.map((r) => `/-- ${r.title} -/\ndef ${constName(r.id)} : String := ${JSON.stringify(r.id)}`),
    "",
    "/-- Every rule id, in catalog order. -/",
    "def all : List String :=",
    "  [ " + catalog.rules.map((r) => constName(r.id)).join("\n  , ") + " ]",
    "",
    "def isRule (s : String) : Bool := all.contains s",
    "",
    "end Guard.R",
    "",
  ];
  return lines.join("\n");
}

function main() {
  const check = process.argv.includes("--check");
  const catalog = loadCatalog();
  const rendered = { js: renderJs(catalog), lean: renderLean(catalog) };
  let stale = [];
  for (const [k, path] of Object.entries(outputs)) {
    const current = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (current !== rendered[k]) {
      if (check) stale.push(path);
      else writeFileSync(path, rendered[k]);
    }
  }
  if (check) {
    if (stale.length) {
      console.error("generated files are stale; run `npm run gen:rules`:\n  " + stale.join("\n  "));
      process.exit(1);
    }
    console.log(`rules: ${catalog.rules.length} ids, generated files current`);
  } else {
    console.log(`rules: ${catalog.rules.length} ids -> ${Object.values(outputs).map((p) => p.replace(root + "/", "")).join(", ")}`);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) main();
