// The editable policy is data in rules/policy.json. Validator algorithms stay
// independently implemented in JS and Lean and are compared behaviorally.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { loadCatalog, constName } from "./gen-rules.mjs";

const root = new URL("../", import.meta.url);
const plain = new Set(["num", "nonNeg", "unit", "lenPct", "path", "transform", "viewBox", "color", "text", "ident", "id", "idRefs", "cls", "lang"]);
const tableKeys = ["htmlGlobal", "svgGlobal", "htmlElements", "svgElements", "htmlForced", "htmlUnwrap", "htmlDropRules", "svgDropRules", "attrDropRules", "svgTextOnly"];
const q = JSON.stringify;
const leanString = s => q(s); // Schema strings are restricted to printable ASCII below.

export function validatePolicy(p) {
  const rules = new Set(loadCatalog().rules.map(r => r.id));
  const fail = msg => { throw new Error(`policy schema: ${msg}`); };
  const string = v => { if (typeof v !== "string" || /[^\x20-\x7e]/.test(v)) fail("expected printable ASCII string"); };
  const descriptor = d => {
    if (!Array.isArray(d)) fail("validator must be a descriptor array");
    const [kind, ...args] = d;
    if (plain.has(kind) && args.length === 0) return;
    if (kind === "tagged" && args.length === 2 && rules.has(args[0])) return descriptor(args[1]);
    if (kind === "oneOf" && args.length === 1 && Array.isArray(args[0]) && args[0].length) { args[0].forEach(string); return; }
    if (kind === "fixed" && args.length === 1) return string(args[0]);
    if (kind === "numList" && args.length === 1 && Number.isSafeInteger(args[0]) && args[0] > 0) return;
    if (kind === "int" && args.length === 2 && args.every(Number.isSafeInteger) && args[0] <= args[1]) return;
    fail(`invalid validator ${q(d)}`);
  };
  const attrs = t => {
    if (!t || Array.isArray(t) || typeof t !== "object") fail("attribute table must be an object");
    for (const [name, d] of Object.entries(t)) {
      if (!/^[A-Za-z][A-Za-z0-9-]*$/.test(name) || name.startsWith("on")) fail(`invalid allowed attribute ${name}`);
      descriptor(d);
    }
  };
  if (p.version !== 1 || Object.keys(p).some(k => !["version", "limits", "sharedGlobal", ...tableKeys].includes(k))) fail("unknown schema version or field");
  const limitKeys = ["maxNodes", "maxDepth", "maxTextLength", "maxTotalText", "maxAttrs", "maxAttrValueLength", "maxPathNumbers", "maxPointsNumbers", "maxNumberMagnitude"];
  if (!p.limits || Object.keys(p.limits).length !== limitKeys.length) fail("unexpected structural limits");
  for (const k of limitKeys) if (!Number.isSafeInteger(p.limits[k]) || p.limits[k] <= 0) fail(`invalid limit ${k}`);
  attrs(p.sharedGlobal); attrs(p.htmlGlobal); attrs(p.svgGlobal);
  for (const k of Object.keys(p.sharedGlobal)) if (Object.hasOwn(p.htmlGlobal, k) || Object.hasOwn(p.svgGlobal, k)) fail(`duplicate shared attribute ${k}`);
  for (const key of ["htmlElements", "svgElements"]) for (const [tag, t] of Object.entries(p[key])) {
    if (!/^[a-z][a-z0-9]*$/.test(tag)) fail(`invalid tag ${tag}`);
    if (t !== null) attrs(t);
  }
  for (const [tag, pairs] of Object.entries(p.htmlForced)) {
    if (!Object.hasOwn(p.htmlElements, tag) || !Array.isArray(pairs)) fail(`invalid forced element ${tag}`);
    for (const [name, value] of pairs) {
      string(name); string(value);
      if (!Object.hasOwn(p.htmlElements[tag] ?? {}, name) && !Object.hasOwn(p.htmlGlobal, name) && !Object.hasOwn(p.sharedGlobal, name)) fail(`forced attribute ${name} is not allowed`);
    }
  }
  for (const key of ["htmlUnwrap", "htmlDropRules", "svgDropRules", "attrDropRules"]) {
    const names = new Set();
    for (const pair of p[key]) {
      if (!Array.isArray(pair) || pair.length !== 2 || !rules.has(pair[1]) || names.has(pair[0])) fail(`invalid ${key} pair`);
      string(pair[0]); names.add(pair[0]);
    }
  }
  for (const name of p.svgTextOnly) if (!Object.hasOwn(p.svgElements, name)) fail(`unknown text-only SVG tag ${name}`);
}

function leanVal(d) {
  const [kind, a, b] = d;
  if (plain.has(kind)) return `.${kind}`;
  if (kind === "tagged") return `.tagged R.${constName(a)} (${leanVal(b)})`;
  if (kind === "oneOf") return `.oneOf [${a.map(leanString).join(", ")}]`;
  if (kind === "fixed") return `.fixed ${leanString(a)}`;
  if (kind === "int") return `.int (${a}) (${b})`;
  return `.numList ${a}`;
}
const leanAttrs = t => `[${Object.entries(t ?? {}).map(([n, d]) => `(${leanString(n)}, ${leanVal(d)})`).join(", ")}]`;
const leanPairs = ps => `[${ps.map(([n, r]) => `(${leanString(n)}, R.${constName(r)})`).join(", ")}]`;
const leanHeader = "/- GENERATED by scripts/gen-policy.mjs from rules/policy.json. Do not edit. -/\n";
const jsNames = { htmlGlobal: "HTML_GLOBAL", svgGlobal: "SVG_GLOBAL", htmlElements: "HTML_ELEMENTS", svgElements: "SVG_ELEMENTS", htmlForced: "HTML_FORCED", htmlUnwrap: "HTML_UNWRAP", htmlDropRules: "HTML_DROP_RULES", svgDropRules: "SVG_DROP_RULES", attrDropRules: "ATTR_DROP_RULES", svgTextOnly: "SVG_TEXT_ONLY" };

export function renderPolicy(p) {
  validatePolicy(p);
  p = { ...p, htmlGlobal: { ...p.sharedGlobal, ...p.htmlGlobal }, svgGlobal: { ...p.sharedGlobal, ...p.svgGlobal } };
  const outputs = new Map();
  outputs.set("src/policy-data.js", "// GENERATED by scripts/gen-policy.mjs. Edit rules/policy.json.\n" +
    `export const POLICY_DATA = ${JSON.stringify(p, null, 2)};\n` +
    "export const POLICY_LIMITS = Object.freeze(POLICY_DATA.limits);\n" +
    "export function createPolicyTables(resolve) {\n" +
    "  const attrs = table => table === null ? null : Object.fromEntries(Object.entries(table).map(([n, d]) => [n, resolve(d)]));\n" +
    "  const elements = table => Object.fromEntries(Object.entries(table).map(([tag, t]) => [tag, attrs(t)]));\n" +
    "  return {\n" + tableKeys.map(k => `    ${jsNames[k]}: ${k.endsWith("Global") ? `attrs(POLICY_DATA.${k})` : k.endsWith("Elements") ? `elements(POLICY_DATA.${k})` : k === "htmlForced" ? `POLICY_DATA.${k}` : k === "svgTextOnly" ? `new Set(POLICY_DATA.${k})` : `new Map(POLICY_DATA.${k})`},`).join("\n") + "\n  };\n}\n");
  outputs.set("lean/Guard/Core/Limits.lean", leanHeader + "\nnamespace Guard\n\nstructure Limits where\n" +
    Object.entries(p.limits).map(([n,v]) => `  ${n} : Nat := ${v}`).join("\n") + "\n\ndef limits : Limits := {}\n\nend Guard\n");
  for (const [ns, file] of [["html", "Html"], ["svg", "Svg"]]) {
    let body = leanHeader + "import Guard.Policy.Val\n\nnamespace Guard\n\nopen V\n\n";
    body += `def ${ns}Global : Table :=\n  [ ` + Object.entries(p[`${ns}Global`]).map(([n,d]) => `(${leanString(n)}, ${leanVal(d)})`).join("\n  , ") + " ]\n\n";
    body += `def ${ns}Elements : List (String × Table) :=\n  [ ` + Object.entries(p[`${ns}Elements`]).map(([tag,t]) => `(${leanString(tag)}, ${leanAttrs(t)})`).join("\n  , ") + " ]\n\n";
    body += `def ${ns}DropRules : List (String × String) :=\n  ${leanPairs(p[`${ns}DropRules`])}\n\n`;
    if (ns === "html") {
      body += `def htmlUnwrap : List (String × String) :=\n  ${leanPairs(p.htmlUnwrap)}\n\n`;
      body += "def htmlForced : List (String × List (String × String)) :=\n  [ " + Object.entries(p.htmlForced).map(([tag,pairs]) => `(${leanString(tag)}, [${pairs.map(([n,v]) => `(${leanString(n)}, ${leanString(v)})`).join(", ")}])`).join("\n  , ") + " ]\n";
    } else {
      body += `def svgTextOnly : List String := [${p.svgTextOnly.map(leanString).join(", ")}]\n\n`;
      body += "def svgCanonical : List (String × String) :=\n  let all : Table := svgGlobal ++ svgElements.foldl (fun acc p => acc ++ p.2) []\n  all.map fun p => (asciiLower p.1, p.1)\n";
    }
    outputs.set(`lean/Guard/Policy/Tables/${file}.lean`, body + "\nend Guard\n");
  }
  outputs.set("lean/Guard/Policy/Tables/Attrs.lean", leanHeader + "import Guard.Rules\n\nnamespace Guard\n\n" +
    `def attrDropRules : List (String × String) :=\n  ${leanPairs(p.attrDropRules)}\n\n` +
    "def dropRuleFor (name : String) : String :=\n  match attrDropRules.lookup name with\n  | some r => r\n  | none =>\n    if name.contains ':' then R.ATTR_NAMESPACED\n    else if name.startsWith \"on\" then R.EXEC_HANDLER\n    else R.ATTR_ALLOWLIST\n\nend Guard\n");
  return outputs;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const p = JSON.parse(readFileSync(new URL("rules/policy.json", root), "utf8"));
  const check = process.argv.includes("--check");
  const stale = [];
  for (const [name, content] of renderPolicy(p)) {
    const file = new URL(name, root);
    if (check) {
      let current = null;
      try { current = readFileSync(file, "utf8"); } catch {}
      if (current !== content) stale.push(name);
    } else writeFileSync(file, content);
  }
  if (stale.length) throw new Error(`stale generated policy: ${stale.join(", ")}; run npm run gen:policy`);
  console.log(`policy: shared tables and limits ${check ? "current" : "generated"}`);
}
