/- GENERATED by scripts/gen-rules.mjs from rules/catalog.json. Do not edit. -/

/-!
Rule ids cited in change records by the policy. `src/rules.js` carries the
same ids for the JavaScript checker; the differential compares them.
-/

namespace Guard.R

/-- Script and SVG animation elements are removed with their content -/
def EXEC_SCRIPT : String := "R-EXEC-SCRIPT"
/-- Event handler attributes are removed -/
def EXEC_HANDLER : String := "R-EXEC-HANDLER"
/-- Elements that load or embed external resources are removed -/
def RES_ELEMENT : String := "R-RES-ELEMENT"
/-- SVG elements that reference resources are removed -/
def RES_SVG_REF : String := "R-RES-SVG-REF"
/-- URL-valued attributes are removed -/
def RES_URL_ATTR : String := "R-RES-URL-ATTR"
/-- Anchors are unwrapped in HTML and removed in SVG -/
def NAV_ANCHOR : String := "R-NAV-ANCHOR"
/-- Forms are unwrapped -/
def NAV_FORM : String := "R-NAV-FORM"
/-- MathML and unknown namespaces are removed with their content -/
def NS_MATHML : String := "R-NS-MATHML"
/-- Elements out of namespace position are removed -/
def NS_POSITION : String := "R-NS-POSITION"
/-- Raw-text elements are removed with their content -/
def RCDATA_RAWTEXT : String := "R-RCDATA-RAWTEXT"
/-- Template elements and their content are removed -/
def RCDATA_TEMPLATE : String := "R-RCDATA-TEMPLATE"
/-- Validated output is never serialized and re-parsed -/
def RCDATA_NO_REPARSE : String := "R-RCDATA-NO-REPARSE"
/-- Attributes not in the element or global table are removed -/
def ATTR_ALLOWLIST : String := "R-ATTR-ALLOWLIST"
/-- Namespaced attributes are removed -/
def ATTR_NAMESPACED : String := "R-ATTR-NAMESPACED"
/-- Style elements are removed with their content -/
def STYLE_ELEMENT : String := "R-STYLE-ELEMENT"
/-- Style attributes are removed and never parsed -/
def STYLE_INLINE : String := "R-STYLE-INLINE"
/-- Class names are restricted to the bundled stylesheet -/
def STYLE_CLASS : String := "R-STYLE-CLASS"
/-- Ids are identifier-shaped and prefixed -/
def CLOBBER_ID_PREFIX : String := "R-CLOBBER-ID-PREFIX"
/-- Name attributes are removed -/
def CLOBBER_NAME : String := "R-CLOBBER-NAME"
/-- Prototype-named attributes are removed and attributes never become object keys -/
def CLOBBER_ATTR_KEYS : String := "R-CLOBBER-ATTR-KEYS"
/-- Depth, node count and text length limits reject the document -/
def LIMIT_TREE : String := "R-LIMIT-TREE"
/-- Attribute count and value length are bounded -/
def LIMIT_ATTRS : String := "R-LIMIT-ATTRS"
/-- Input types are restricted -/
def CTRL_INPUT_TYPE : String := "R-CTRL-INPUT-TYPE"
/-- Autocomplete is forced off -/
def CTRL_AUTOCOMPLETE : String := "R-CTRL-AUTOCOMPLETE"
/-- Buttons are always type=button -/
def CTRL_BUTTON_TYPE : String := "R-CTRL-BUTTON-TYPE"
/-- Focus-stealing attributes are removed -/
def CTRL_FOCUS : String := "R-CTRL-FOCUS"
/-- Control and bidi characters are stripped -/
def TEXT_CONTROL_BIDI : String := "R-TEXT-CONTROL-BIDI"
/-- Numeric attributes are canonical bounded decimals -/
def VAL_NUMBER : String := "R-VAL-NUMBER"
/-- Paint values are solid colors only -/
def VAL_COLOR : String := "R-VAL-COLOR"
/-- Path data is commands and bounded numbers only -/
def VAL_PATH : String := "R-VAL-PATH"
/-- Transforms are known functions with numeric arguments -/
def VAL_TRANSFORM : String := "R-VAL-TRANSFORM"
/-- Enumerated and identifier attributes are closed sets -/
def VAL_KEYWORD : String := "R-VAL-KEYWORD"
/-- Comments, doctypes and unknown nodes are removed -/
def STRUCT_NON_ELEMENT : String := "R-STRUCT-NON-ELEMENT"
/-- Elements not in the allowlist are removed or unwrapped -/
def STRUCT_ELEMENT_ALLOWLIST : String := "R-STRUCT-ELEMENT-ALLOWLIST"
/-- The runtime exposes no host capabilities -/
def RT_ISOLATION : String := "R-RT-ISOLATION"
/-- Runtime resources are bounded -/
def RT_LIMITS : String := "R-RT-LIMITS"
/-- Host data is a frozen global -/
def RT_FROZEN_DATA : String := "R-RT-FROZEN-DATA"
/-- Unsupported programs are rejected with diagnostics -/
def GATE_INTERFACE : String := "R-GATE-INTERFACE"
/-- Only policy fixed points are rendered -/
def FRAME_FIXED_POINT : String := "R-FRAME-FIXED-POINT"
/-- Frame messages are source-checked and schema-checked -/
def FRAME_MESSAGE_SCHEMA : String := "R-FRAME-MESSAGE-SCHEMA"
/-- The frame is sandboxed, CSP-pinned and sink-hardened -/
def FRAME_CSP_SINKS : String := "R-FRAME-CSP-SINKS"
/-- The renderer never parses markup -/
def RENDER_CONSTRUCTORS_ONLY : String := "R-RENDER-CONSTRUCTORS-ONLY"
/-- Accepted output satisfies the structural policy and is a fixed point -/
def CHECK_ACCEPTANCE : String := "R-CHECK-ACCEPTANCE"

/-- Every rule id, in catalog order. -/
def all : List String :=
  [ EXEC_SCRIPT
  , EXEC_HANDLER
  , RES_ELEMENT
  , RES_SVG_REF
  , RES_URL_ATTR
  , NAV_ANCHOR
  , NAV_FORM
  , NS_MATHML
  , NS_POSITION
  , RCDATA_RAWTEXT
  , RCDATA_TEMPLATE
  , RCDATA_NO_REPARSE
  , ATTR_ALLOWLIST
  , ATTR_NAMESPACED
  , STYLE_ELEMENT
  , STYLE_INLINE
  , STYLE_CLASS
  , CLOBBER_ID_PREFIX
  , CLOBBER_NAME
  , CLOBBER_ATTR_KEYS
  , LIMIT_TREE
  , LIMIT_ATTRS
  , CTRL_INPUT_TYPE
  , CTRL_AUTOCOMPLETE
  , CTRL_BUTTON_TYPE
  , CTRL_FOCUS
  , TEXT_CONTROL_BIDI
  , VAL_NUMBER
  , VAL_COLOR
  , VAL_PATH
  , VAL_TRANSFORM
  , VAL_KEYWORD
  , STRUCT_NON_ELEMENT
  , STRUCT_ELEMENT_ALLOWLIST
  , RT_ISOLATION
  , RT_LIMITS
  , RT_FROZEN_DATA
  , GATE_INTERFACE
  , FRAME_FIXED_POINT
  , FRAME_MESSAGE_SCHEMA
  , FRAME_CSP_SINKS
  , RENDER_CONSTRUCTORS_ONLY
  , CHECK_ACCEPTANCE ]

def isRule (s : String) : Bool := all.contains s

end Guard.R
