/- GENERATED by scripts/gen-policy.mjs from rules/policy.json. Do not edit. -/
import Guard.Rules

namespace Guard

def attrDropRules : List (String × String) :=
  [("src", R.RES_URL_ATTR), ("srcset", R.RES_URL_ATTR), ("href", R.RES_URL_ATTR), ("xlink:href", R.RES_URL_ATTR), ("poster", R.RES_URL_ATTR), ("data", R.RES_URL_ATTR), ("code", R.RES_URL_ATTR), ("background", R.RES_URL_ATTR), ("ping", R.RES_URL_ATTR), ("formaction", R.RES_URL_ATTR), ("action", R.RES_URL_ATTR), ("content", R.RES_URL_ATTR), ("http-equiv", R.RES_URL_ATTR), ("longdesc", R.RES_URL_ATTR), ("cite", R.RES_URL_ATTR), ("manifest", R.RES_URL_ATTR), ("style", R.STYLE_INLINE), ("name", R.CLOBBER_NAME), ("__proto__", R.CLOBBER_ATTR_KEYS), ("constructor", R.CLOBBER_ATTR_KEYS), ("prototype", R.CLOBBER_ATTR_KEYS), ("autofocus", R.CTRL_FOCUS), ("accesskey", R.CTRL_FOCUS), ("contenteditable", R.CTRL_FOCUS), ("draggable", R.CTRL_FOCUS)]

def dropRuleFor (name : String) : String :=
  match attrDropRules.lookup name with
  | some r => r
  | none =>
    if name.contains ':' then R.ATTR_NAMESPACED
    else if name.startsWith "on" then R.EXEC_HANDLER
    else R.ATTR_ALLOWLIST

end Guard
