/- GENERATED by scripts/gen-policy.mjs from rules/policy.json. Do not edit. -/
import Guard.Policy.Val

namespace Guard

open V

def svgGlobal : Table :=
  [ ("class", .cls)
  , ("id", .id)
  , ("role", .oneOf ["img", "figure", "group", "list", "listitem", "table", "row", "cell", "columnheader", "rowheader", "tablist", "tab", "tabpanel", "button", "presentation", "none", "status", "region", "heading", "note", "switch", "radiogroup", "toolbar", "separator", "graphics-document", "graphics-object", "graphics-symbol"])
  , ("tabindex", .tagged R.CTRL_FOCUS (.oneOf ["0", "-1"]))
  , ("data-action", .ident)
  , ("data-value", .text)
  , ("data-key", .text)
  , ("data-hover", .fixed "")
  , ("aria-label", .text)
  , ("aria-labelledby", .idRefs)
  , ("aria-describedby", .idRefs)
  , ("aria-controls", .idRefs)
  , ("aria-hidden", .oneOf ["true", "false"])
  , ("aria-expanded", .oneOf ["true", "false"])
  , ("aria-selected", .oneOf ["true", "false"])
  , ("aria-pressed", .oneOf ["true", "false", "mixed"])
  , ("aria-checked", .oneOf ["true", "false", "mixed"])
  , ("aria-disabled", .oneOf ["true", "false"])
  , ("aria-current", .oneOf ["true", "false", "page", "step", "location", "date", "time"])
  , ("aria-live", .oneOf ["off", "polite"])
  , ("aria-sort", .oneOf ["ascending", "descending", "none", "other"])
  , ("aria-valuenow", .num)
  , ("aria-valuemin", .num)
  , ("aria-valuemax", .num)
  , ("aria-valuetext", .text)
  , ("aria-level", .int (1) (6))
  , ("aria-orientation", .oneOf ["horizontal", "vertical"])
  , ("aria-roledescription", .text)
  , ("transform", .transform)
  , ("fill", .color)
  , ("stroke", .color)
  , ("fill-opacity", .unit)
  , ("stroke-opacity", .unit)
  , ("opacity", .unit)
  , ("stroke-width", .nonNeg)
  , ("stroke-linecap", .oneOf ["butt", "round", "square"])
  , ("stroke-linejoin", .oneOf ["miter", "round", "bevel"])
  , ("stroke-dasharray", .numList 16)
  , ("fill-rule", .oneOf ["nonzero", "evenodd"])
  , ("pointer-events", .oneOf ["none", "all", "visiblePainted"])
  , ("font-size", .nonNeg)
  , ("font-family", .oneOf ["sans-serif", "serif", "monospace"])
  , ("font-weight", .oneOf ["normal", "bold", "400", "600", "700"])
  , ("text-anchor", .oneOf ["start", "middle", "end"])
  , ("dominant-baseline", .oneOf ["auto", "middle", "central", "hanging", "alphabetic"]) ]

def svgElements : List (String × Table) :=
  [ ("svg", [("viewBox", .viewBox), ("width", .lenPct), ("height", .lenPct), ("preserveAspectRatio", .oneOf ["none", "xMidYMid meet", "xMinYMin meet", "xMidYMid slice"])])
  , ("g", [])
  , ("title", [])
  , ("desc", [])
  , ("rect", [("x", .num), ("y", .num), ("width", .nonNeg), ("height", .nonNeg), ("rx", .nonNeg), ("ry", .nonNeg)])
  , ("circle", [("cx", .num), ("cy", .num), ("r", .nonNeg)])
  , ("ellipse", [("cx", .num), ("cy", .num), ("rx", .nonNeg), ("ry", .nonNeg)])
  , ("line", [("x1", .num), ("y1", .num), ("x2", .num), ("y2", .num)])
  , ("polyline", [("points", .numList 2000)])
  , ("polygon", [("points", .numList 2000)])
  , ("path", [("d", .path)])
  , ("text", [("x", .numList 1), ("y", .numList 1), ("dx", .numList 1), ("dy", .numList 1), ("rotate", .numList 1), ("textLength", .nonNeg)])
  , ("tspan", [("x", .numList 1), ("y", .numList 1), ("dx", .numList 1), ("dy", .numList 1)]) ]

def svgDropRules : List (String × String) :=
  [("script", R.EXEC_SCRIPT), ("animate", R.EXEC_SCRIPT), ("set", R.EXEC_SCRIPT), ("animatetransform", R.EXEC_SCRIPT), ("animatemotion", R.EXEC_SCRIPT), ("discard", R.EXEC_SCRIPT), ("style", R.STYLE_ELEMENT), ("image", R.RES_SVG_REF), ("use", R.RES_SVG_REF), ("feimage", R.RES_SVG_REF), ("textpath", R.RES_SVG_REF), ("pattern", R.RES_SVG_REF), ("filter", R.RES_SVG_REF), ("mask", R.RES_SVG_REF), ("marker", R.RES_SVG_REF), ("clippath", R.RES_SVG_REF), ("lineargradient", R.RES_SVG_REF), ("radialgradient", R.RES_SVG_REF), ("a", R.NAV_ANCHOR), ("foreignobject", R.NS_POSITION)]

def svgTextOnly : List String := ["title", "desc"]

def svgCanonical : List (String × String) :=
  let all : Table := svgGlobal ++ svgElements.foldl (fun acc p => acc ++ p.2) []
  all.map fun p => (asciiLower p.1, p.1)

end Guard
